apiVersion: apps/v1
kind: Deployment
metadata:
  name:  react-ui
  namespace: ms
  labels:
    app:  react-ui
spec:
  selector:
    matchLabels:
      app: react-ui
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  react-ui
    spec:
      containers:
       - name:  react-ui
         image:  badrul11/ui-web-app-reactjs:latest
         ports:
          - containerPort:  8090
            name:  react-ui 
