apiVersion: v1
kind: Service
metadata:
  name: react-ui
  namespace: ms
spec:
  selector:
    app: react-ui
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: react-ui
    port: 8090
    targetPort: 8090 
