apiVersion: v1
kind: Service
metadata:
  name: zuul-api-gateway
  namespace: ms
spec:
  selector:
    app: zuul-api-gateway
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: zuul-api-gateway
    port: 9999
    targetPort: 9999
    nodePort: 32470
